blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('detail/<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': 'True', 'null': 'True'}


class Blog(models.Model):
    user_admin = User.objects.filter(is_superuser=True).first().pk

    title = models.CharField(max_length=150, unique=True, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug')
    message = models.TextField(verbose_name='содержимое', **NULLABLE)
    preview = models.ImageField(upload_to='blog/', verbose_name='превью', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=False, verbose_name='опубликовано (да/нет)')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')
    owner = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=user_admin, verbose_name='Автор')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        permissions = [
            (
                'content_manager',
                'can published, update, delete in blog'
             )
        ]

blog/forms.py
from django import forms

from blog.models import Blog
from catalog.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ('slug', 'created_at', 'views_count', 'owner',)
        labels = {
            'title': 'Заголовок статьи',
            'message': 'Текст статьи',
            'preview': 'Превью для статьи',
            'is_published': 'Опубликовано',
        }

blog/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogForm
from blog.models import Blog


def is_author_or_manager(request):
    pk = int(request.path.split('/')[-1])
    is_author = Blog.objects.get(pk=pk).owner == request.user
    is_content_manager = request.user.has_perm('blog.content_manager')
    return is_author or is_content_manager


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm

    def get_form(self, form_class=None):
        form = super().get_form()
        if not self.request.user.has_perm('blog.content_manager'):
            form.fields['is_published'].disabled = True
        return form

    def get_success_url(self, *args, **kwargs):
        return reverse('blog:detail', args={self.object.pk})

    def form_valid(self, form):
        if form.is_valid:
            new_blog = form.save(commit=False)
            new_blog.slug = slugify(new_blog.title)
            new_blog.owner = self.request.user
            new_blog.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_authenticated:
            queryset = queryset.filter(is_published=True)
        elif not self.request.user.has_perm('blog.content_manager'):
            queryset = queryset.filter(is_published=True) | queryset.filter(owner=self.request.user)
        queryset = queryset.order_by('-created_at', )
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        if self.object.views_count == 100:
            send_mail(
                '100 просмотров',
                f'Статья ({self.object.pk})"{self.object.title}" набрала 100 просмотров.',
                settings.EMAIL_HOST_USER,
                ['a.kolmychek@gmail.com']
            )
        return self.object


class BlogUpdateView(UserPassesTestMixin, UpdateView):
    model = Blog
    form_class = BlogForm

    def test_func(self):
        return is_author_or_manager(self.request)

    def get_form(self, form_class=None):
        form = super().get_form()
        if not self.request.user.has_perm('blog.content_manager'):
            form.fields['is_published'].disabled = True
        return form

    def get_success_url(self):
        return reverse('blog:detail', args=[self.kwargs['pk']])


class BlogDeleteView(UserPassesTestMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

    def test_func(self):
        return is_author_or_manager(self.request)

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block internal_navigation %}
{% endblock %}

{% block content %}

<div class="container my-5">


    <h1>Уверены, что хотите удалить эту статью?</h1>

    <div class="d-flex pt-2">

        <form method="post">
            {% csrf_token %}
            {{form}}
            <input type="submit" class="btn btn-danger bg-red btn-lg border-0" value="Удалить">
        </form>
        <a href="{% url 'blog:list' %}"
           class="text-white btn btn-success bg-dark-green btn-lg border-0 ms-3">
            Отмена</a>
    </div>

</div>

<div class="container bg-green my-5">
    <div class="row p-3">
        {% include 'blog/includes/inc_blog_detail.html' %}
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block internal_navigation %}
{% endblock %}

{% block content %}

<div class="container bg-green my-5">
    <div class="row p-3">
        {% include 'blog/includes/inc_blog_detail.html' %}
    </div>
    <div class="d-flex pb-3 px-3">
        <a href="{% url 'blog:list' %}" class="text-white">К списку статей</a>
        {% if perms.blog.content_manager or object.owner == request.user %}
        <a href="{% url 'blog:update' object.pk %}" class="text-white ps-4">Редактировать статью</a>
        {% endif %}
        {% if request.user.is_authenticated %}
        <a href="{% url 'blog:create' %}" class="text-white ps-4">Создать статью</a>
        {% endif %}
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load blog_tags %}

{% block internal_navigation %}
{% endblock %}

{% block content %}
<div class="container bg-green my-5">
    <h1 class="text-white p-3">
        {% if object %}
        Редактирование статьи
        {% else %}
        Добавление новой статьи
        {% endif %}
    </h1>

    <div class="row">
        <div class="col-7">

            <form method="POST" class="p-3 fs-5 needs-validation" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-light my-3">
                    {% if object %}
                    Изменить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </form>
        </div>

        <div class="col-5 p-5">
            <img src="{% static 'blog/img/create_article_icon.png' %}" class="img-fluid p-5">
        </div>
    </div>
    <div class="row-col p-3">
        <a href="{% url 'blog:list' %}" class="text-white">К списку статей</a>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load blog_tags %}

{% block internal_navigation %}
{% endblock %}


{% block content %}
<div class="container my-5 text-white">
    <div class="row bg-green">
        <div class="col-7 p-5 align-self-center">
            <p class="fs-1">Блог про овощи и фрукты</p>
            <p class="fs-5">Здесь собраны интересные и полезные статьи про овощи, фрукти и орехи.
                Вы сможете найти новые рецепты вкусных блюд и массу другой ценной информации.</p>
        </div>
        <div class="col-5 p-3">
            <img src="{% static 'blog/img/img_list.png' %}" class="img-fluid"/>
        </div>
    </div>
</div>

<div class="container pb-5">
    <div class="row row-cols-4 g-4">
        {% for object in object_list %}
        <div class="col">
            <div class="card bg-light-green h-100">

                <a href="{% url 'blog:detail' object.pk %}">
                    {% if object.preview != '' %}
                    <img src="{{ object.preview|mediapath }}"
                         class="card-img-top img-fluid p-3">
                    {% else %}
                    <img src="{% static 'blog/img/article_list_img_default.png' %}"
                         class="card-img-top img-fluid p-3">
                    {% endif %}
                </a>
                <div class="card-body pt-0">
                    <h5 class="card-title">{{ object.title }}</h5>
                    <hr>
                    <p class="card-text">{{ object.message|safe|truncatechars:100 }}</p>
                    <p class="card-text text-end">{{ object.created_at|date:'d E Y' }}</p>
                </div>
                <div class="card-footer text-center">
                    <a href="{% url 'blog:detail' object.pk %}"
                       class="btn btn-success bg-dark-green
                                      text-white border-0">
                        Посмотреть
                    </a>
                    {% if perms.blog.content_manager or object.owner == request.user %}
                    <a href="{% url 'blog:update' object.pk %}"
                       class="btn btn-warning bg-custom-btn-orange border-0">
                        <i class="bi bi-pencil"></i>
                    </a>
                    <a href="{% url 'blog:delete' object.pk %}"
                       class="btn btn-warning bg-custom-btn-orange border-0">
                        <i class="bi bi-trash3"></i>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}

        {% if request.user.is_authenticated %}
        <div class="col">
            <div class="card bg-light-orange h-100">
                <a href="{% url 'blog:create' %}">
                    <img src="{% static 'blog/img/new_article_icon.png' %}"
                         class="card-img-top img-fluid p-3">
                </a>
                <div class="card-body pt-0">
                    <h5 class="card-title">Новая статья</h5>
                    <hr>
                    <p class="card-text">Здесь вы можете перейти к созданию новой записи.</p>
                </div>
                <div class="card-footer text-center">
                    <a href="{% url 'blog:create' %}"
                       class="btn btn-warning bg-orange
                                      text-white border-0">
                        Создать статью
                    </a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}