blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('detail/<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, UserQuestionCreateView, \
    ProductUpdateView, HarvestCreateView, HarvestUpdateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contact/', UserQuestionCreateView.as_view(), name='contact'),
    path('view/<int:pk>', ProductDetailView.as_view(), name='view'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='update'),
    path('create_harvest/<int:product_pk>', HarvestCreateView.as_view(), name='create_harvest'),
    path('update_harvest/<int:pk>', HarvestUpdateView.as_view(), name='update_harvest'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from users.forms import UserLoginForm
from users.views import RegisterView, ProfileView, password_reset, password_reset_done, confirm_email, confirm_email_start

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html', authentication_form=UserLoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password_reset/', password_reset, name='password_reset'),
    path('password_reset_done/', password_reset_done, name='password_reset_done'),
    path('confirm_email/', confirm_email, name='confirm_email'),
    path('confirm_email_start/', confirm_email_start, name='confirm_email_start'),
]

catalog/models.py
from datetime import date

from django.db import models

from users.models import User

NULLABLE = {'null': 'True', 'blank': 'True'}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']


class Product(models.Model):
    user_admin = User.objects.filter(is_superuser=True).first().pk

    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='products/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='id категории')
    price = models.IntegerField(verbose_name='Цена', **NULLABLE)
    created_at = models.DateField(verbose_name='Дата создания', auto_now_add=True)
    changed_at = models.DateField(verbose_name='Дата изменения', auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=user_admin, verbose_name='Автор')
    is_published = models.BooleanField(verbose_name='Опубликовано (да/нет)', default=False)

    def __str__(self):
        return f'{self.name}'

    @property
    def current_harvest(self):
        return self.harvest_set.filter(is_current=True).last()

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['category', 'name']
        permissions = [
            (
                'moderator',
                'can change is_published, description, category'
            )
        ]


class CompanyContact(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    icon_bootstrap = models.CharField(max_length=100, verbose_name='Иконка Bootstrap')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class UserQuestion(models.Model):
    user_name = models.CharField(max_length=150, verbose_name='Имя')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    email = models.EmailField(verbose_name='Почта')
    question = models.TextField(verbose_name='Вопрос')
    created_at = models.DateField(verbose_name='Дата', auto_now_add=True)

    def __str__(self):
        return f'{self.user_name}: {self.question[:20]}'

    class Meta:
        verbose_name = 'Вопрос пользователя'
        verbose_name_plural = 'Вопросы пользователей'


class Harvest(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    harvest_number = models.IntegerField(verbose_name='Номер')
    harvest_date = models.DateField(verbose_name='Дата сбора урожая')
    is_current = models.BooleanField(default=False, verbose_name='Текущая поставка (да/нет)')

    def __str__(self):
        return f'({self.harvest_number}) {self.harvest_date} - {self.product}'

    class Meta:
        verbose_name = 'Поставка'
        verbose_name_plural = 'Поставки'

catalog/forms.py
from django import forms

from catalog.models import Product, UserQuestion, Harvest
from const import FORBIDDEN_WORDS_IN_FORMS


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field.widget, forms.widgets.Textarea):
                field.widget.attrs['rows'] = 3
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input m-2'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'changed_at', 'owner', )
        labels = {
            'name': 'Наименование',
            'description': 'Описание продукта',
            'image': 'Изображение продукта',
            'category': 'Категория',
            'price': 'Цена (₽/кг)',
        }

    def clean(self):
        cleaned_data = super().clean()
        name_description = cleaned_data.get('name') + cleaned_data.get('description')

        for word in FORBIDDEN_WORDS_IN_FORMS:
            if word in name_description:
                raise forms.ValidationError('В тексте не должно быть запрещенных слов')

        return cleaned_data


class UserQuestionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = UserQuestion
        exclude = ('created_at',)
        labels = {
            'user_name': 'Ваше имя',
            'phone': 'Телефон для связи',
            'email': 'Почта для связи',
            'question': 'Ваш вопрос',
        }

class HarvestForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Harvest
        fields = '__all__'

    def clean_is_current(self):
        cleaned_data = self.cleaned_data['is_current']

        print(len(self.cleaned_data['product'].harvest_set.filter(is_current=True)))
        if (cleaned_data):
            if len(self.cleaned_data['product'].harvest_set.filter(is_current=True)) > 0:
                raise forms.ValidationError('У продукта может быть только одна текущая поставка')

        return cleaned_data

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from catalog.forms import ProductForm, UserQuestionForm, HarvestForm
from catalog.models import Category, Product, CompanyContact, UserQuestion, Harvest


class ProductListView(ListView):
    model = Product

    def get_context_data(self):
        data = []
        categories = Category.objects.all()
        print(self.request.user.has_perm('catalog.can_moderate'))
        for category in categories:
            products = Product.objects.filter(category=category.pk)
            if not self.request.user.is_authenticated:
                products = products.filter(is_published=True)
            elif not self.request.user.has_perm('catalog.can_moderate'):
                products = products.filter(owner=self.request.user) | products.filter(is_published=True)
            data.append({
                'category': category,
                'products': products
            })
        data = sorted(data, key=lambda item: item['category'].pk)
        return {'data': data}


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm

    def get_form(self, form_class=None):
        form = super().get_form()
        if not self.request.user.has_perm('catalog.can_moderate'):
            form.fields['is_published'].disabled = True
        return form

    def get_success_url(self):
        return reverse('catalog:view', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        new_product = form.save(commit=False)
        new_product.owner = self.request.user
        new_product.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_form(self, form_class=None):
        form = super().get_form()
        if self.request.user.has_perm('catalog.can_moderate'):
            form.fields['name'].disabled = True
            form.fields['image'].disabled = True
            form.fields['price'].disabled = True
        else:
            form.fields['is_published'].disabled = True
        return form

    def test_func(self):
        pk = int(self.request.path.split('/')[-1])
        is_author = Product.objects.get(pk=pk).owner == self.request.user
        can_moderate = self.request.user.has_perm('catalog.can_moderate')
        return is_author or can_moderate

    def get_success_url(self):
        return reverse_lazy('catalog:view', args=[self.kwargs['pk']])


class UserQuestionCreateView(CreateView):
    model = UserQuestion
    form_class = UserQuestionForm
    company_contacts = CompanyContact.objects.all()
    company_contacts = sorted(company_contacts, key=lambda item: item.pk)
    extra_context = {'cont': company_contacts}
    success_url = reverse_lazy('catalog:contact')


class HarvestCreateView(CreateView):
    model = Harvest
    form_class = HarvestForm

    def get_success_url(self):
        return reverse('catalog:view', args=[self.kwargs['product_pk']])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['initial']['product'] = Product.objects.get(pk=self.kwargs['product_pk'])
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        context['product'] = Product.objects.get(pk=self.kwargs['product_pk'])
        return context


class HarvestUpdateView(UpdateView):
    model = Harvest
    form_class = HarvestForm

    def get_success_url(self):
        return reverse_lazy('catalog:view', args=[self.object.product.pk])

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Магазинчик</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="{% static 'custom_css/custom_styles.css' %}" rel="stylesheet">
</head>


<body class="d-flex flex-column min-vh-100">
<header class="container">
    <div class="row">
        {% include 'catalog/includes/inc_main_menu.html' %}
        <nav id="navbar" class="navbar">
            <div class="col-3">
                <p class=" text-uppercase fs-3 text-color-green m-0" href="/"><b>Магазинчик</b></p>
            </div>
            <div class="col-5">
                {% block internal_navigation %}
                {% endblock %}
            </div>
            <div class="col-4  text-end">
                {% if user.is_authenticated %}
                   <a class="btn btn-outline-secondary me-2" href="{% url 'users:logout' %}">Выйти</a>
                   <a class="btn btn-outline-secondary me-2" href="{% url 'users:profile' %}">Профиль</a>
                {% else %}
                   <a class="btn btn-outline-secondary me-2" href="{% url 'users:login' %}">Войти</a>
                   <a class="btn btn-outline-secondary me-2" href="{% url 'users:register' %}">Регистрация</a>
                {% endif %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </div>
</header>


<main role="main">
    {% block content %}
    {% endblock %}
</main>


<footer class="container-fluid mt-auto bg-green py-2">
    <div class="container">
        <div class="row">
            <div class="col-8 text-center fs-5">
                &copy; Company 2023–{% now 'Y' %}
            </div>
            <div class="col-4 fs-5">
                <a href="#" class="float-end link-offset-2 link-dark
                link-underline-opacity-25 link-underline-opacity-100-hover">
                    Наверх
                </a>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/harvest_form.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load catalog_tags %}

{% block internal_navigation %}
{% endblock %}

{% block content %}
<div class="container bg-green my-5">
    <h1 class="text-white p-3">
        {% if object %}
        Редактирование поставки
        {% else %}
        Добавление новой поставки
        {% endif %}
    </h1>

    <div class="row">
        <div class="col-6">
            <form method="POST" class="p-3 fs-5 needs-validation" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn btn-light my-3">
                    {% if object %}
                    Изменить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
                <a href="{% url 'catalog:index' %}" class="btn btn-light my-3">
                    На главную
                </a>
            </form>
        </div>

        {% if object %}
        <div class="col-6 px-5 pt-1 fs-5">
            <h4 class="text-white">Информаци о продукте</h4>
            <h3>Категория: {{ harvest.product.category|lower }}</h3>
            <h1 class="pt-4">{{ harvest.product.name }}</h1>
            <p class="fs-5">{{ harvest.product.description }}</p>
            <h3 class="py-4">Цена: {{ harvest.product.price }} ₽/кг</h3>
            <p>Первые поставки: {{ harvest.product.created_at|date:'d.m.Y' }}<br/>
                Последние изменения {{ harvest.product.changed_at|date:'d.m.Y' }}</p>
        </div>
        {% else %}
        <div class="col-6 px-5 pt-1 fs-5">
            <h4 class="text-white">Информаци о продукте</h4>
            <h3>Категория: {{ product.category|lower }}</h3>
            <h1 class="pt-4">{{ product.name }}</h1>
            <p class="fs-5">{{ product.description }}</p>
            <h3 class="py-4">Цена: {{ product.price }} ₽/кг</h3>
            <p>Первые поставки: {{ product.created_at|date:'d.m.Y' }}<br/>
                Последние изменения {{ product.changed_at|date:'d.m.Y' }}</p>
        </div>
        {% endif %}

    </div>
</div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% load static %}


{% block internal_navigation %}
<ul class="nav justify-content-center">
    {% for item in data %}
    <li class="nav-item">
        <a class="nav-link link-body-emphasis fs-5"
           href="#{{ item.category.pk }}">
            {{ item.category.name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}


{% block content %}
<div class="container my-5 text-white">
    <div class="row bg-green">
        <div class="col-6 p-5 align-self-center">
            <p class="fs-1">Отборные фрукты и овощи с&nbsp;доставкой</p>
            <p class="fs-5">Только свежие, вкусные, отборные овощи и&nbsp;фрукты. С&nbsp;доставкой в&nbsp;день
                заказа.</p>
        </div>
        <div class="col-6">
            <img src="{% static 'catalog/img/main_image.png' %}" class="img-fluid"/>
        </div>
    </div>
</div>

{% for item in data %}
<div class="{% bg_light_color forloop.counter %} py-3">
    <div class="container">
        <h1 id="{{ item.category.pk }}" class="py-3 {% text_color forloop.counter %}">
            {{ item.category.name }}
        </h1>

        <div class="container pb-5">
            <div class="row row-cols-4 g-4">
                {% for product in item.products %}
                <div class="col">
                    <div class="card {% bg_light_color forloop.parentloop.counter %} h-100" >

                        <a href="{% url 'catalog:product' product_id=product.pk %}">
                            <img src="{% mediapath product.image %}"
                             class="card-img-top img-fluid pt-3">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name|slice:':23' }}</h5>
                            <p class="card-text">Цена: {{ product.price }} ₽/кг</p>
                            <a href="#"
                               class="btn btn-warning
                                      {% bg_dark_color forloop.parentloop.counter %}
                                      text-white border-0">
                                Добавить в корзину
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/new_product.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block internal_navigation %}
{% endblock %}

{% block content %}
<div class="container bg-green my-5">
    <h1 class="text-white p-3">Добавление нового продукта</h1>

    <div class="row">
        <div class="col-7">

            <form method="POST" class="p-3 fs-5 needs-validation" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="productName" class="form-label">Наименование</label>
                    <input type="text" name="name" class="form-control" id="productName" required>
                </div>

                <div class="mb-3">
                    <label for="productCategory" class="form-label">Категория продукта</label>
                    <select class="form-select" id="productCategory" name="category">
                        {% for category in categories %}
                        <option value="{{ category.pk }}">{{ category.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="mb-3">
                    <label for="productDescription" class="form-label">Описание продукта</label>
                    <textarea class="form-control" name="description" id="productDescription" rows="3"></textarea>
                </div>

                <div class="mb-3">
                    <label for="productImage" class="form-label">Изображение продукта</label>
                    <input type="file" name="image" class="form-control" id="productImage">
                </div>

                <div class="mb-3">
                    <label for="productPrice" class="form-label">Цена (₽/кг)</label>
                    <input type="number" name="price" class="form-control" id="productPrice"
                           data-bind="value:replyNumber" min="0">
                </div>

                <button type="submit" class="btn btn-light my-3">Добавить</button>
            </form>
        </div>

        <div class="col-5 p-5">
            <img src="{% static 'catalog/img/new_product_icon.png' %}" class="img-fluid p-5" alt="Новый продукт">
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load catalog_tags%}

{% block internal_navigation %}
{% endblock %}

{% block content %}
<div class="container bg-green my-5">
    <div class="row p-3">
        <div class="col-6 text-white">
            <h3>Категория: {{ product.category|lower }}</h3>
            <h1 class="pt-4">{{ product.name }}</h1>
            <p class="fs-5">{{ product.description }}</p>
            <h3 class="py-4">Цена: {{ product.price }} ₽/кг</h3>
            <p>Первые поставки: {{ product.created_at|date:'d.m.Y' }}<br/>
                Последние изменения {{ product.changed_at|date:'d.m.Y' }}</p>
            <a href="{% url 'catalog:index' %}" class="text-white">На главную</a>
            <a href="{% url 'catalog:new_product' %}" class="text-white px-4">Добавить продукт</a>
        </div>
        <div class="col-6 p-0 text-end align-self-center">
            <img src="{% mediapath product.image%}" class="img-fluid" alt="{{ product.name }}">
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load catalog_tags%}

{% block internal_navigation %}
{% endblock %}

{% block content %}
<div class="container bg-green my-5">
    <div class="row p-3">
        <div class="col-6 text-white">
            <h3>Категория: {{ object.category|lower }}</h3>
            <h1 class="pt-4">{{ object.name }}</h1>
            <p class="fs-5">{{ object.description }}</p>
            <h3 class="py-4">Цена:
                {% if object.price %}
                    {{ object.price }} ₽/кг
                {% else %}
                    не указана
                {% endif %}
            {% if object.current_harvest %}
            <br>Cбор урожая: {{ object.current_harvest.harvest_date|date:'d.m.Y' }}
            {% endif %}
            </h3>
            <p>Первые поставки: {{ object.created_at|date:'d.m.Y' }}<br/>
                Последние изменения: {{ object.changed_at|date:'d.m.Y' }}</p>
            <a href="{% url 'catalog:index' %}" class="text-white">На главную</a>

            {% if perms.proudct_can_moderate or product.owner == user %}
            <a href="{% url 'catalog:update' object.pk %}" class="text-white ps-4">Изменить продукт</a>
            {% endif %}
            {% if request.user.is_authenticated %}
            <a href="{% url 'catalog:create' %}" class="text-white ps-4">Добавить продукт</a>
            {% endif %}
        </div>
        <div class="col-6 p-0 text-end align-self-center">
            <img src="{% mediapath product.image%}" class="img-fluid" alt="{{ product.name }}">
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load catalog_tags %}

{% block internal_navigation %}
{% endblock %}

{% block content %}
<div class="container bg-green my-5">
    <h1 class="text-white p-3">
        {% if object %}
        Редактирование продукта
        {% else %}
        Добавление нового продукта
        {% endif %}
    </h1>

    <div class="row">
        <div class="col-6">
            <form method="POST" class="p-3 fs-5 needs-validation" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn btn-light my-3">
                    {% if object %}
                    Изменить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
                <a href="{% url 'catalog:index' %}" class="btn btn-light my-3">
                    На главную
                </a>
            </form>
        </div>

        {% if object %}
        <div class="col-6 px-5 pt-1 fs-5">
            <h4 class="text-white">Информаци о поставке / сборе урожая</h4>
            {% for harvest in object.harvest_set.all %}
            <table style="width:100%">
                <tr>
                    <td>Номер поставки</td>
                    <td>{{ harvest.harvest_number }}</td>
                    <td rowspan="3">
                        <a href="{% url 'catalog:update_harvest' harvest.pk %}" class="btn btn-outline-dark my-3">
                            <i class="bi bi-pencil"></i>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>Дата сбора урожая</td>
                    <td>{{ harvest.harvest_date }}</td>
                </tr>
                <tr>
                    <td>Текущая поставка</td>
                    <td><input class="form-check-input" type="checkbox"
                               {% if harvest.is_current %}
                               checked
                               {% endif %}
                               disabled></td>
                </tr>
            </table>
            <hr>
            {% endfor %}
            <div class="d-grid col-6 mx-auto">
                <a href="{% url 'catalog:create_harvest' object.pk %}" class="btn btn-outline-dark btn-block">
                Завести новую поставку
            </a>
            </div>

        </div>
        {% else %}
        <div class="col-6 p-5 fs-5">
            <img src="{% static 'catalog/img/new_product_icon.png' %}" class="img-fluid p-5" alt="Новый продукт">
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% load static %}


{% block internal_navigation %}
<ul class="nav justify-content-center">
    {% for item in data %}
    <li class="nav-item">
        <a class="nav-link link-body-emphasis fs-5"
           href="#{{ item.category.pk }}">
            {{ item.category.name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}


{% block content %}
<div class="container my-5 text-white">
    <div class="row bg-green">
        <div class="col-6 p-5 align-self-center">
            <p class="fs-1">Отборные фрукты и овощи с&nbsp;доставкой</p>
            <p class="fs-5">Только свежие, вкусные, отборные овощи и&nbsp;фрукты. С&nbsp;доставкой в&nbsp;день
                заказа.</p>
        </div>
        <div class="col-6">
            <img src="{% static 'catalog/img/main_image.png' %}" class="img-fluid"/>
        </div>
    </div>
</div>

{% for item in data %}
<div class="{% bg_light_color forloop.counter %} py-3">
    <div class="container">
        <h1 id="{{ item.category.pk }}" class="py-3 {% text_color forloop.counter %}">
            {{ item.category.name }}
        </h1>

        <div class="container pb-5">
            <div class="row row-cols-4 g-4">
                {% for product in item.products %}
                <div class="col">
                    <div class="card {% bg_light_color forloop.parentloop.counter %} h-100">

                        <a href="{% url 'catalog:view' product.pk %}">
                            <img src="{% mediapath product.image %}"
                                 class="card-img-top img-fluid pt-3">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name|slice:':23' }}</h5>
                            <p class="card-text mb-0">Цена: {{ product.price }} ₽/кг</p>
                            {% if product.current_harvest %}
                            <p class="card-text">Cбор урожая: {{ product.current_harvest.harvest_date|date:'d.m.Y' }}</p>
                            {% endif %}
                        </div>
                        <div class="card-footer text-center">
                            <a href="#"
                               class="btn btn-warning
                                      {% bg_dark_color forloop.parentloop.counter %}
                                      text-white border-0">
                                Добавить в корзину
                            </a>
                            {% if perms.catalog.can_moderate or product.owner == user %}
                            <a href="{% url 'catalog:update' product.pk %}"
                               class="btn btn-warning
                                      {% bg_dark_color forloop.parentloop.counter %}
                                      text-white border-0">
                                <i class="bi bi-pencil"></i>
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/userquestion_form.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block internal_navigation %}
{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row">
        <div class="col-7 bg-green">
            <div class="row row-cols-2 text-white h-100">
                {% for item in cont %}
                <div class="col p-4 align-self-center">
                    <h3><i class="bi {{ item.icon_bootstrap }}"></i> {{ item.name }}</h3>
                    <p class="fs-5">{{ item.description | linebreaks }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-5 px-4">
            <h3>Задать вопрос здесь</h3>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success bg-dark-green text-white border-0">Отправить</button>
            </form>
        </div>
    </div>
    <div>
        <img src="{% static 'catalog/img/food_contacts.png' %}" class="img-fluid">
    </div>
</div>
{% endblock %}